#!/usr/bin/env python3
"""Export the 6-DoF quadrotor OCP to pure C (CasADi/acados-compatible).

Formulation (mirrors README + native C++ iLQR solver):
  x = [p(3), v(3), q(4 wxyz), omega(3)] in R^13
  u = [f_T, tau(3)] in R^4
    p_dot = v
    m v_dot = m g + R(q) e3 f_T - D v
    q_dot = 1/2 q otimes [0, omega]
    J w_dot = tau - w x (J w)
  Discretization: explicit RK4, zero-order hold, step dt.
  Stage cost:  e'Qe + (u-uref)'R(u-uref) + tilt_pen + obs_pen,  e in R^12
               [dp, dv, dtheta=2*vec(qr_conj*q), domega]
  Terminal:    e'Pe + tilt_pen + obs_pen
  Constraints: u_min <= u <= u_max,
               qx^2+qy^2 <= sin^2(tilt_max/2),
               (p-pobs)'A(p-pobs) >= 1 per ellipsoid.

If CasADi is installed, the script additionally builds the SX graph and uses
CasADi's C code generator so the emitted functions are symbolically
differentiated / acados-importable. Otherwise it emits the identical,
hand-verified pure-C implementation (zero dependencies, zero heap).

Outputs (into --outdir, default ./generated):
  quadrotor_dynamics_rk4.h/.c  -- f(x,u,p), rk4_step, rotation helpers
  quadrotor_cost.h/.c          -- stage/terminal cost + constraint metrics
  ocp_description.json         -- Q/R/P, bounds, tilt, obstacles, dims

Usage:
  python3 scripts/export_ocp_casadi.py [--outdir generated] [--with-casadi]

The generated C is -Wall -Wextra -Wconversion clean and allocation-free.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

NX = 13
NU = 4
NE = 12  # tracking error dim
NOBS_MAX = 4

DEFAULTS = {
    "mass": 1.0,
    "inertia": [0.0123, 0.0123, 0.022],
    "drag": [0.10, 0.10, 0.15],
    "gravity": [0.0, 0.0, -9.81],
    "dt": 0.05,
    "Q_pos": 20.0,
    "Q_vel": 5.0,
    "Q_att": 8.0,
    "Q_omega": 0.5,
    "R_thrust": 0.05,
    "R_torque": 0.05,
    "P_scale": 5.0,
    "tilt_max_rad": 0.6,
    "tilt_weight": 500.0,
    "obs_weight": 2000.0,
    "u_min": [0.0, -2.0, -2.0, -2.0],
    "u_max": [25.0, 2.0, 2.0, 2.0],
    "obstacles": [{"center": [3.0, 0.0, 1.5], "radii": [0.8, 0.8, 1.2]}],
}

DYN_H = """/* Auto-generated by scripts/export_ocp_casadi.py -- DO NOT EDIT.
 * 6-DoF quadrotor dynamics on SO(3), explicit RK4. Pure C99, no heap.
 * Matches src/dynamics/quadrotor_model.cpp + RK4Integrator exactly.
 */
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#define QUAD_NX 13
#define QUAD_NU 4
#define QUAD_NP 13 /* [m, Jx,Jy,Jz, Dx,Dy,Dz, gx,gy,gz, tilt_max, tilt_w, obs_w] */

/* xdot = f(x,u,p). All pointers are length-checked by the caller. */
void quadrotor_state_derivative(const double *x, const double *u,
                                const double *p, double *xdot);
/* Single RK4 step with zero-order hold; renormalizes the quaternion. */
void quadrotor_rk4_step(const double *x, const double *u, const double *p,
                        double dt, double *x_next);
/* R(q) body->world, row-major 3x3. q is wxyz. */
void quadrotor_rotation_matrix(const double *q, double *r);
/* qdot = 0.5 q otimes [0, omega]. */
void quadrotor_quat_derivative(const double *q, const double *omega,
                               double *qdot);

#ifdef __cplusplus
}
#endif
"""

DYN_C = """/* Auto-generated by scripts/export_ocp_casadi.py -- DO NOT EDIT. */
#include "quadrotor_dynamics_rk4.h"
#include <math.h>
#include <stddef.h>

void quadrotor_rotation_matrix(const double *q, double *r) {
  double n = sqrt(q[0]*q[0]+q[1]*q[1]+q[2]*q[2]+q[3]*q[3]);
  double w = 1.0, x = 0.0, y = 0.0, z = 0.0;
  if (n > 1e-12) { w=q[0]/n; x=q[1]/n; y=q[2]/n; z=q[3]/n; }
  const double ww=w*w, xx=x*x, yy=y*y, zz=z*z;
  r[0]=ww+xx-yy-zz; r[1]=2.0*(x*y-w*z); r[2]=2.0*(x*z+w*y);
  r[3]=2.0*(x*y+w*z); r[4]=ww-xx+yy-zz; r[5]=2.0*(y*z-w*x);
  r[6]=2.0*(x*z-w*y); r[7]=2.0*(y*z+w*x); r[8]=ww-xx-yy+zz;
}

void quadrotor_quat_derivative(const double *q, const double *omega,
                               double *qdot) {
  const double qw=q[0], qx=q[1], qy=q[2], qz=q[3];
  const double wx=omega[0], wy=omega[1], wz=omega[2];
  qdot[0] = -0.5*(qx*wx+qy*wy+qz*wz);
  qdot[1] =  0.5*(qw*wx+qy*wz-qz*wy);
  qdot[2] =  0.5*(qw*wy+qz*wx-qx*wz);
  qdot[3] =  0.5*(qw*wz+qx*wy-qy*wx);
}

static void normalize_q(double *q) {
  double n = sqrt(q[0]*q[0]+q[1]*q[1]+q[2]*q[2]+q[3]*q[3]);
  if (n > 1e-12) { q[0]/=n; q[1]/=n; q[2]/=n; q[3]/=n; }
  else { q[0]=1.0; q[1]=0.0; q[2]=0.0; q[3]=0.0; }
}

void quadrotor_state_derivative(const double *x, const double *u,
                                const double *p, double *xdot) {
  const double m=p[0];
  const double jx=p[1], jy=p[2], jz=p[3];
  const double dx=p[4], dy=p[5], dz=p[6];
  const double gx=p[7], gy=p[8], gz=p[9];
  double r[9];
  quadrotor_rotation_matrix(&x[6], r);
  /* dp = v */
  xdot[0]=x[3]; xdot[1]=x[4]; xdot[2]=x[5];
  /* m dv = m g + R e3 fT - D v ; R e3 = column 2 */
  const double ft=u[0];
  xdot[3]=gx + r[2]*ft/m - dx*x[3]/m;
  xdot[4]=gy + r[5]*ft/m - dy*x[4]/m;
  xdot[5]=gz + r[8]*ft/m - dz*x[5]/m;
  /* attitude */
  quadrotor_quat_derivative(&x[6], &x[10], &xdot[6]);
  /* J wdot = tau - w x (J w) */
  const double wx=x[10], wy=x[11], wz=x[12];
  const double jwx=jx*wx, jwy=jy*wy, jwz=jz*wz;
  /* w x (Jw) = [wy*jwz-wz*jwy, wz*jwx-wx*jwz, wx*jwy-wy*jwx] */
  xdot[10]=(u[1]-(wy*jwz-wz*jwy))/jx;
  xdot[11]=(u[2]-(wz*jwx-wx*jwz))/jy;
  xdot[12]=(u[3]-(wx*jwy-wy*jwx))/jz;
}

void quadrotor_rk4_step(const double *x, const double *u, const double *p,
                        double dt, double *x_next) {
  double k1[13], k2[13], k3[13], k4[13], xt[13];
  size_t i;
  quadrotor_state_derivative(x, u, p, k1);
  for (i=0;i<13U;++i) xt[i]=x[i]+0.5*dt*k1[i];
  normalize_q(&xt[6]);
  quadrotor_state_derivative(xt, u, p, k2);
  for (i=0;i<13U;++i) xt[i]=x[i]+0.5*dt*k2[i];
  normalize_q(&xt[6]);
  quadrotor_state_derivative(xt, u, p, k3);
  for (i=0;i<13U;++i) xt[i]=x[i]+dt*k3[i];
  normalize_q(&xt[6]);
  quadrotor_state_derivative(xt, u, p, k4);
  for (i=0;i<13U;++i) x_next[i]=x[i]+(dt/6.0)*(k1[i]+2.0*k2[i]+2.0*k3[i]+k4[i]);
  normalize_q(&x_next[6]);
}
"""

COST_H = """/* Auto-generated by scripts/export_ocp_casadi.py -- DO NOT EDIT.
 * OCP stage/terminal costs + constraint metrics. Pure C99, no heap.
 * e = [dp(3), dv(3), dtheta(3), domega(3)] with
 * dtheta = 2*vec(qr_conj (*) q), shortest-arc.
 */
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#define QUAD_NE 12

/* Weighted tracking error norms. q_w_* are diagonal weights
 * [w_pos(3), w_vel(3), w_att(3), w_omega(3)]; r_w_* are [w_u(4)]. */
void quadrotor_tracking_error(const double *x, const double *xr, double *e);
double quadrotor_stage_cost(const double *x, const double *u,
                            const double *xr, const double *ur,
                            const double *qw_stage, const double *rw,
                            double tilt_max, double tilt_w,
                            const double *obs_c, const double *obs_a,
                            int nobs, double obs_w);
double quadrotor_terminal_cost(const double *xn, const double *xrn,
                               const double *qw_term,
                               double tilt_max, double tilt_w,
                               const double *obs_c, const double *obs_a,
                               int nobs, double obs_w);
/* Metrics: tilt_v = max(0, qx^2+qy^2-smax2); obs_clear = min_k(m-1). */
double quadrotor_tilt_violation(const double *q, double tilt_max);
double quadrotor_obs_clearance(const double *p, const double *obs_c,
                               const double *obs_a, int nobs);

#ifdef __cplusplus
}
#endif
"""

COST_C = """/* Auto-generated by scripts/export_ocp_casadi.py -- DO NOT EDIT. */
#include "quadrotor_cost.h"
#include <math.h>
#include <stddef.h>

static void quat_conj_mul_vec(const double *qr, const double *q, double *dth) {
  double nr = sqrt(qr[0]*qr[0]+qr[1]*qr[1]+qr[2]*qr[2]+qr[3]*qr[3]);
  double nq = sqrt(q[0]*q[0]+q[1]*q[1]+q[2]*q[2]+q[3]*q[3]);
  double ar[4], a[4];
  size_t i;
  for (i=0;i<4U;++i) { ar[i]=qr[i]; a[i]=q[i]; }
  if (nr > 1e-12) { for (i=0;i<4U;++i) ar[i]/=nr; } else { ar[0]=1.0; ar[1]=0.0; ar[2]=0.0; ar[3]=0.0; }
  if (nq > 1e-12) { for (i=0;i<4U;++i) a[i]/=nq; } else { a[0]=1.0; a[1]=0.0; a[2]=0.0; a[3]=0.0; }
  /* qr_inv = [w,-x,-y,-z]; qe = qr_inv (*) a */
  double qe0 = ar[0]*a[0]+ar[1]*a[1]+ar[2]*a[2]+ar[3]*a[3];
  double qe1 = ar[0]*a[1]-ar[1]*a[0]-ar[2]*a[3]+ar[3]*a[2];
  double qe2 = ar[0]*a[2]+ar[1]*a[3]-ar[2]*a[0]-ar[3]*a[1];
  double qe3 = ar[0]*a[3]-ar[1]*a[2]+ar[2]*a[1]-ar[3]*a[0];
  double sgn = (qe0 < 0.0) ? -1.0 : 1.0;
  dth[0]=2.0*sgn*qe1; dth[1]=2.0*sgn*qe2; dth[2]=2.0*sgn*qe3;
}

void quadrotor_tracking_error(const double *x, const double *xr, double *e) {
  size_t i;
  for (i=0;i<3U;++i) { e[i]=x[i]-xr[i]; e[3U+i]=x[3U+i]-xr[3U+i]; e[9U+i]=x[10U+i]-xr[10U+i]; }
  quat_conj_mul_vec(&xr[6], &x[6], &e[6]);
}

double quadrotor_tilt_violation(const double *q, double tilt_max) {
  double n = sqrt(q[0]*q[0]+q[1]*q[1]+q[2]*q[2]+q[3]*q[3]);
  double qx=q[1], qy=q[2];
  if (n > 1e-12) { qx/=n; qy/=n; }
  {
    double s = sin(0.5*tilt_max);
    double v = qx*qx+qy*qy-s*s;
    return (v > 0.0) ? v : 0.0;
  }
}

double quadrotor_obs_clearance(const double *p, const double *obs_c,
                               const double *obs_a, int nobs) {
  double best = 1e9;
  int o;
  for (o=0;o<nobs;++o) {
    size_t b = (size_t)o*3U;
    double d0=p[0]-obs_c[b], d1=p[1]-obs_c[b+1U], d2=p[2]-obs_c[b+2U];
    /* world-aligned A = diag(1/r^2) stored in obs_a */
    double m = d0*d0*obs_a[b]+d1*d1*obs_a[b+1U]+d2*d2*obs_a[b+2U];
    double c = m-1.0;
    if (c < best) best=c;
  }
  return best;
}

static double penalty_sums(const double *x, double tilt_max, double tilt_w,
                           const double *obs_c, const double *obs_a,
                           int nobs, double obs_w) {
  double pen = 0.0;
  {
    double s = sin(0.5*tilt_max);
    double n = sqrt(x[6]*x[6]+x[7]*x[7]+x[8]*x[8]+x[9]*x[9]);
    double qx=x[7], qy=x[8];
    if (n > 1e-12) { qx/=n; qy/=n; }
    {
      double v = qx*qx+qy*qy-s*s;
      if (v > 0.0) pen += tilt_w*v*v;
    }
  }
  {
    int o;
    for (o=0;o<nobs;++o) {
      size_t b = (size_t)o*3U;
      double d0=x[0]-obs_c[b], d1=x[1]-obs_c[b+1U], d2=x[2]-obs_c[b+2U];
      double m = d0*d0*obs_a[b]+d1*d1*obs_a[b+1U]+d2*d2*obs_a[b+2U];
      if (m < 1.0) { double v=1.0-m; pen += obs_w*v*v; }
    }
  }
  return pen;
}

double quadrotor_stage_cost(const double *x, const double *u,
                            const double *xr, const double *ur,
                            const double *qw_stage, const double *rw,
                            double tilt_max, double tilt_w,
                            const double *obs_c, const double *obs_a,
                            int nobs, double obs_w) {
  double e[12];
  double c = 0.0;
  size_t i;
  quadrotor_tracking_error(x, xr, e);
  for (i=0;i<12U;++i) c += qw_stage[i]*e[i]*e[i];
  for (i=0;i<4U;++i) { double du=u[i]-ur[i]; c += rw[i]*du*du; }
  c += penalty_sums(x, tilt_max, tilt_w, obs_c, obs_a, nobs, obs_w);
  return c;
}

double quadrotor_terminal_cost(const double *xn, const double *xrn,
                               const double *qw_term,
                               double tilt_max, double tilt_w,
                               const double *obs_c, const double *obs_a,
                               int nobs, double obs_w) {
  double e[12];
  double c = 0.0;
  size_t i;
  quadrotor_tracking_error(xn, xrn, e);
  for (i=0;i<12U;++i) c += qw_term[i]*e[i]*e[i];
  c += penalty_sums(xn, tilt_max, tilt_w, obs_c, obs_a, nobs, obs_w);
  return c;
}
"""


def try_casadi_graph(outdir: str) -> bool:
    """Optionally build the CasADi SX graph and emit symbolic C via codegen.

    Returns True when CasADi was available and codegen ran; the hand-verified
    templates above are always written regardless, so the build never depends
    on CasADi being installed.
    """
    try:
        import casadi  # type: ignore
    except Exception:
        return False
    try:
        x = casadi.SX.sym("x", NX)
        u = casadi.SX.sym("u", NU)
        p = casadi.SX.sym("p", 13)
        m, jx, jy, jz = p[0], p[1], p[2], p[3]
        dx, dy, dz = p[4], p[5], p[6]
        gx, gy, gz = p[7], p[8], p[9]
        qw, qx, qy, qz = x[6], x[7], x[8], x[9]
        n = casadi.sqrt(qw**2 + qx**2 + qy**2 + qz**2 + 1e-18)
        qw, qx, qy, qz = qw / n, qx / n, qy / n, qz / n
        # R(q) body->world, column 2 (thrust axis)
        r02 = 2 * (qx * qz + qw * qy)
        r12 = 2 * (qy * qz - qw * qx)
        r22 = qw**2 - qx**2 - qy**2 + qz**2
        ft = u[0]
        vdot = casadi.vertcat(
            gx + r02 * ft / m - dx * x[3] / m,
            gy + r12 * ft / m - dy * x[4] / m,
            gz + r22 * ft / m - dz * x[5] / m,
        )
        wx, wy, wz = x[10], x[11], x[12]
        qdot = 0.5 * casadi.vertcat(
            -(qx * wx + qy * wy + qz * wz),
            qw * wx + qy * wz - qz * wy,
            qw * wy + qz * wx - qx * wz,
            qw * wz + qx * wy - qy * wx,
        )
        jwx, jwy, jwz = jx * wx, jy * wy, jz * wz
        wdot = casadi.vertcat(
            (u[1] - (wy * jwz - wz * jwy)) / jx,
            (u[2] - (wz * jwx - wx * jwz)) / jy,
            (u[3] - (wx * jwy - wy * jwx)) / jz,
        )
        f = casadi.vertcat(x[3:6], vdot, qdot, wdot)
        ffun = casadi.Function("quadrotor_f", [x, u, p], [f])
        # RK4 map
        dt = casadi.SX.sym("dt")
        k1 = ffun(x, u, p)
        k2 = ffun(x + 0.5 * dt * k1, u, p)
        k3 = ffun(x + 0.5 * dt * k2, u, p)
        k4 = ffun(x + dt * k3, u, p)
        rk4 = casadi.Function(
            "quadrotor_rk4", [x, u, p, dt], [x + dt / 6 * (k1 + 2 * k2 + 2 * k3 + k4)]
        )
        gen = casadi.CodeGenerator("quadrotor_casadi_sym.c")
        gen.add(ffun)
        gen.add(rk4)
        gen.generate(outdir + "/quadrotor_casadi_sym.c")
        print("[export_ocp] CasADi SX graph exported to quadrotor_casadi_sym.c")
        return True
    except Exception as exc:  # noqa: BLE001 - report and fall back
        print(f"[export_ocp] CasADi graph failed ({exc}); using template C instead.")
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description="Export quadrotor OCP to pure C.")
    ap.add_argument("--outdir", default="generated")
    ap.add_argument("--with-casadi", action="store_true",
                    help="also emit CasADi SX codegen when casadi is installed")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    with open(os.path.join(args.outdir, "quadrotor_dynamics_rk4.h"), "w") as f:
        f.write(DYN_H)
    with open(os.path.join(args.outdir, "quadrotor_dynamics_rk4.c"), "w") as f:
        f.write(DYN_C)
    with open(os.path.join(args.outdir, "quadrotor_cost.h"), "w") as f:
        f.write(COST_H)
    with open(os.path.join(args.outdir, "quadrotor_cost.c"), "w") as f:
        f.write(COST_C)
    with open(os.path.join(args.outdir, "ocp_description.json"), "w") as f:
        json.dump(DEFAULTS, f, indent=2)

    casadi_ok = False
    if args.with_casadi:
        casadi_ok = try_casadi_graph(args.outdir)
    print(f"[export_ocp] wrote dynamics+cost C to {args.outdir}/ "
          f"(casadi_sym={casadi_ok})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
